{{- define "meeting-trans-poc.realtime.envSecret" -}}
SONIOX_API_KEY: {{ .Values.soniox.apiKey | quote }}
SUPABASE_SERVICE_ROLE_KEY: {{ .Values.supabase.serviceRoleKey | quote }}
{{- end -}}

{{- include "tplchart.secret" (dict
  "Args" (dict
    "nameTemplate" "%s-realtime"
    "stringData" (include "meeting-trans-poc.realtime.envSecret" .)
  )
  "context" .
) -}}
